### ISSUE TITLE
HTML syntax support?

### ISSUE THREAD

**Issue by rcrooks** [stuartthompson/statn-penta#1]
Beautiful color scheme. Will support for HTML syntax be coming?

**Comment by stuartthompson** [comment]
@rcrooks Thank you! Yes, I'm planning to add support for the following over the next week:

- HTML
- TypeScript
- GoLang
- Java

I'll be adding more support for other languages after that, as well as styling some more elements in the editor (input boxes, debug window states, etc). This is my first extension so I'm learning a lot as I go.

**Comment by stuartthompson** [comment]
This is addressed in: https://github.com/stuartthompson/statn-penta/pull/2/commits/bdc92a32ed87c6cd4f04ef0f93848a02d4baee77
